### ISSUE TITLE
Post-repair problem

### ISSUE THREAD

**Issue by goneclick** [mrmin123/kancolle-auto#153]
After repair is finished, bot instantly tries to sortie. So when bot goes from menu to combat page the ship is still displayed as being repaired. Afterwards, bot proceeds to go to resupply page even though it hasn't sortied and loop timer starts.

**Comment by mrmin123** [comment]
So it's just a matter of it not refreshing home before trying to sortie, right?

**Comment by mrmin123** [comment]
This 1-line change should fix it: https://github.com/mrmin123/kancolle-auto/compare/153_postrepair?expand=1#diff-5f0e6770239d03699703cf40c6b460f6L197

**Comment by Aftersky** [comment]
This issue still occurs somewhat frequently in recent versions. The bot tries to sortie with one ship still displayed as being repaired and crash with find_failed error because the combat_start button is grayed out.

**Comment by mrmin123** [comment]
Strange. Is the ship being repaired done with the repair and it's a matter of kancolle-auto not refreshing home, or is the ship being repaired nowhere near being finished?

**Comment by Aftersky** [comment]
@mrmin123 Yes the ship is repaired but kancolle didn't refresh, it went straight from home > sortie screen and crash.

**Comment by mrmin123** [comment]
Hopefully fixed in the 2016-05-11 update.
